// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataDate = "data_date"

// DataDate mapped from table <data_date>
type DataDate struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ShipName string `gorm:"column:ship_name;not null" json:"ship_name"`
	Date     int64  `gorm:"column:date" json:"date"`
}

// TableName DataDate's table name
func (*DataDate) TableName() string {
	return TableNameDataDate
}
