// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDbMigration = "db_migrations"

// DbMigration mapped from table <db_migrations>
type DbMigration struct {
	MigrationName string    `gorm:"column:migration_name;primaryKey" json:"migration_name"`
	AppliedAt     time.Time `gorm:"column:applied_at" json:"applied_at"`
}

// TableName DbMigration's table name
func (*DbMigration) TableName() string {
	return TableNameDbMigration
}
