// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoilRegion = "soil_regions"

// SoilRegion 土质区域划分表
type SoilRegion struct {
	ID       int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	XMin     float64 `gorm:"column:x_min;not null" json:"x_min"`
	XMax     float64 `gorm:"column:x_max;not null" json:"x_max"`
	YMin     float64 `gorm:"column:y_min;not null" json:"y_min"`
	YMax     float64 `gorm:"column:y_max;not null" json:"y_max"`
	ZMin     float64 `gorm:"column:z_min;not null" json:"z_min"`
	ZMax     float64 `gorm:"column:z_max;not null" json:"z_max"`
	SoilType string  `gorm:"column:soil_type;not null;comment:土质" json:"soil_type"` // 土质
}

// TableName SoilRegion's table name
func (*SoilRegion) TableName() string {
	return TableNameSoilRegion
}
