// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTheoryOptimalParam = "theory_optimal_params"

// TheoryOptimalParam 理论最优施工参数表
type TheoryOptimalParam struct {
	ID                           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                     // 主键ID
	CreatedAt                    time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                   // 创建时间
	UpdatedAt                    time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                                   // 更新时间
	DeletedAt                    gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                   // 删除时间
	ShipName                     string         `gorm:"column:ship_name;not null;comment:船名" json:"ship_name"`                                              // 船名
	Flow                         float64        `gorm:"column:flow;comment:流量(m³/h)" json:"flow"`                                                           // 流量(m³/h)
	Concentration                float64        `gorm:"column:concentration;comment:浓度(%)" json:"concentration"`                                            // 浓度(%)
	SPumpRpm                     float64        `gorm:"column:s_pump_rpm;comment:水下泵转速(rpm)" json:"s_pump_rpm"`                                             // 水下泵转速(rpm)
	CutterDepth                  float64        `gorm:"column:cutter_depth;comment:绞刀深度(m)" json:"cutter_depth"`                                            // 绞刀深度(m)
	CarriageTravel               float64        `gorm:"column:carriage_travel;comment:台车行程(m)" json:"carriage_travel"`                                      // 台车行程(m)
	HorizontalSpeed              float64        `gorm:"column:horizontal_speed;comment:横移速度(m/min)" json:"horizontal_speed"`                                // 横移速度(m/min)
	BoosterPumpDischargePressure float64        `gorm:"column:booster_pump_discharge_pressure;comment:升压泵排出压力(bar)" json:"booster_pump_discharge_pressure"` // 升压泵排出压力(bar)
	VacuumDegree                 float64        `gorm:"column:vacuum_degree;comment:真空度(kPa)" json:"vacuum_degree"`                                         // 真空度(kPa)
}

// TableName TheoryOptimalParam's table name
func (*TheoryOptimalParam) TableName() string {
	return TableNameTheoryOptimalParam
}
