// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dredger/model"
)

func newDbMigration(db *gorm.DB, opts ...gen.DOOption) dbMigration {
	_dbMigration := dbMigration{}

	_dbMigration.dbMigrationDo.UseDB(db, opts...)
	_dbMigration.dbMigrationDo.UseModel(&model.DbMigration{})

	tableName := _dbMigration.dbMigrationDo.TableName()
	_dbMigration.ALL = field.NewAsterisk(tableName)
	_dbMigration.MigrationName = field.NewString(tableName, "migration_name")
	_dbMigration.AppliedAt = field.NewTime(tableName, "applied_at")

	_dbMigration.fillFieldMap()

	return _dbMigration
}

type dbMigration struct {
	dbMigrationDo

	ALL           field.Asterisk
	MigrationName field.String
	AppliedAt     field.Time

	fieldMap map[string]field.Expr
}

func (d dbMigration) Table(newTableName string) *dbMigration {
	d.dbMigrationDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dbMigration) As(alias string) *dbMigration {
	d.dbMigrationDo.DO = *(d.dbMigrationDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dbMigration) updateTableName(table string) *dbMigration {
	d.ALL = field.NewAsterisk(table)
	d.MigrationName = field.NewString(table, "migration_name")
	d.AppliedAt = field.NewTime(table, "applied_at")

	d.fillFieldMap()

	return d
}

func (d *dbMigration) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dbMigration) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 2)
	d.fieldMap["migration_name"] = d.MigrationName
	d.fieldMap["applied_at"] = d.AppliedAt
}

func (d dbMigration) clone(db *gorm.DB) dbMigration {
	d.dbMigrationDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dbMigration) replaceDB(db *gorm.DB) dbMigration {
	d.dbMigrationDo.ReplaceDB(db)
	return d
}

type dbMigrationDo struct{ gen.DO }

type IDbMigrationDo interface {
	gen.SubQuery
	Debug() IDbMigrationDo
	WithContext(ctx context.Context) IDbMigrationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDbMigrationDo
	WriteDB() IDbMigrationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDbMigrationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDbMigrationDo
	Not(conds ...gen.Condition) IDbMigrationDo
	Or(conds ...gen.Condition) IDbMigrationDo
	Select(conds ...field.Expr) IDbMigrationDo
	Where(conds ...gen.Condition) IDbMigrationDo
	Order(conds ...field.Expr) IDbMigrationDo
	Distinct(cols ...field.Expr) IDbMigrationDo
	Omit(cols ...field.Expr) IDbMigrationDo
	Join(table schema.Tabler, on ...field.Expr) IDbMigrationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDbMigrationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDbMigrationDo
	Group(cols ...field.Expr) IDbMigrationDo
	Having(conds ...gen.Condition) IDbMigrationDo
	Limit(limit int) IDbMigrationDo
	Offset(offset int) IDbMigrationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDbMigrationDo
	Unscoped() IDbMigrationDo
	Create(values ...*model.DbMigration) error
	CreateInBatches(values []*model.DbMigration, batchSize int) error
	Save(values ...*model.DbMigration) error
	First() (*model.DbMigration, error)
	Take() (*model.DbMigration, error)
	Last() (*model.DbMigration, error)
	Find() ([]*model.DbMigration, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DbMigration, err error)
	FindInBatches(result *[]*model.DbMigration, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DbMigration) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDbMigrationDo
	Assign(attrs ...field.AssignExpr) IDbMigrationDo
	Joins(fields ...field.RelationField) IDbMigrationDo
	Preload(fields ...field.RelationField) IDbMigrationDo
	FirstOrInit() (*model.DbMigration, error)
	FirstOrCreate() (*model.DbMigration, error)
	FindByPage(offset int, limit int) (result []*model.DbMigration, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDbMigrationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dbMigrationDo) Debug() IDbMigrationDo {
	return d.withDO(d.DO.Debug())
}

func (d dbMigrationDo) WithContext(ctx context.Context) IDbMigrationDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dbMigrationDo) ReadDB() IDbMigrationDo {
	return d.Clauses(dbresolver.Read)
}

func (d dbMigrationDo) WriteDB() IDbMigrationDo {
	return d.Clauses(dbresolver.Write)
}

func (d dbMigrationDo) Session(config *gorm.Session) IDbMigrationDo {
	return d.withDO(d.DO.Session(config))
}

func (d dbMigrationDo) Clauses(conds ...clause.Expression) IDbMigrationDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dbMigrationDo) Returning(value interface{}, columns ...string) IDbMigrationDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dbMigrationDo) Not(conds ...gen.Condition) IDbMigrationDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dbMigrationDo) Or(conds ...gen.Condition) IDbMigrationDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dbMigrationDo) Select(conds ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dbMigrationDo) Where(conds ...gen.Condition) IDbMigrationDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dbMigrationDo) Order(conds ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dbMigrationDo) Distinct(cols ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dbMigrationDo) Omit(cols ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dbMigrationDo) Join(table schema.Tabler, on ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dbMigrationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dbMigrationDo) RightJoin(table schema.Tabler, on ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dbMigrationDo) Group(cols ...field.Expr) IDbMigrationDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dbMigrationDo) Having(conds ...gen.Condition) IDbMigrationDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dbMigrationDo) Limit(limit int) IDbMigrationDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dbMigrationDo) Offset(offset int) IDbMigrationDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dbMigrationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDbMigrationDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dbMigrationDo) Unscoped() IDbMigrationDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dbMigrationDo) Create(values ...*model.DbMigration) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dbMigrationDo) CreateInBatches(values []*model.DbMigration, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dbMigrationDo) Save(values ...*model.DbMigration) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dbMigrationDo) First() (*model.DbMigration, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DbMigration), nil
	}
}

func (d dbMigrationDo) Take() (*model.DbMigration, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DbMigration), nil
	}
}

func (d dbMigrationDo) Last() (*model.DbMigration, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DbMigration), nil
	}
}

func (d dbMigrationDo) Find() ([]*model.DbMigration, error) {
	result, err := d.DO.Find()
	return result.([]*model.DbMigration), err
}

func (d dbMigrationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DbMigration, err error) {
	buf := make([]*model.DbMigration, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dbMigrationDo) FindInBatches(result *[]*model.DbMigration, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dbMigrationDo) Attrs(attrs ...field.AssignExpr) IDbMigrationDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dbMigrationDo) Assign(attrs ...field.AssignExpr) IDbMigrationDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dbMigrationDo) Joins(fields ...field.RelationField) IDbMigrationDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dbMigrationDo) Preload(fields ...field.RelationField) IDbMigrationDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dbMigrationDo) FirstOrInit() (*model.DbMigration, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DbMigration), nil
	}
}

func (d dbMigrationDo) FirstOrCreate() (*model.DbMigration, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DbMigration), nil
	}
}

func (d dbMigrationDo) FindByPage(offset int, limit int) (result []*model.DbMigration, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dbMigrationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dbMigrationDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dbMigrationDo) Delete(models ...*model.DbMigration) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dbMigrationDo) withDO(do gen.Dao) *dbMigrationDo {
	d.DO = *do.(*gen.DO)
	return d
}
