// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dredger/model"
)

func newDredgerDataHl(db *gorm.DB, opts ...gen.DOOption) dredgerDataHl {
	_dredgerDataHl := dredgerDataHl{}

	_dredgerDataHl.dredgerDataHlDo.UseDB(db, opts...)
	_dredgerDataHl.dredgerDataHlDo.UseModel(&model.DredgerDataHl{})

	tableName := _dredgerDataHl.dredgerDataHlDo.TableName()
	_dredgerDataHl.ALL = field.NewAsterisk(tableName)
	_dredgerDataHl.ID = field.NewInt64(tableName, "id")
	_dredgerDataHl.ShipName = field.NewString(tableName, "ship_name")
	_dredgerDataHl.RecordTime = field.NewInt64(tableName, "record_time")
	_dredgerDataHl.LeftEarDraft = field.NewFloat64(tableName, "left_ear_draft")
	_dredgerDataHl.UnderwaterPumpSuctionSealPressure = field.NewFloat64(tableName, "underwater_pump_suction_seal_pressure")
	_dredgerDataHl.UnderwaterPumpShaftSealPressure = field.NewFloat64(tableName, "underwater_pump_shaft_seal_pressure")
	_dredgerDataHl.MudPump1ShaftSealPressure = field.NewFloat64(tableName, "mud_pump_1_shaft_seal_pressure")
	_dredgerDataHl.MudPump1SuctionSealPressure = field.NewFloat64(tableName, "mud_pump_1_suction_seal_pressure")
	_dredgerDataHl.MudPump2SuctionSealPressure = field.NewFloat64(tableName, "mud_pump_2_suction_seal_pressure")
	_dredgerDataHl.MudPump2ShaftSealPressure = field.NewFloat64(tableName, "mud_pump_2_shaft_seal_pressure")
	_dredgerDataHl.RightEarDraft = field.NewFloat64(tableName, "right_ear_draft")
	_dredgerDataHl.LeftAnchorRodAngle = field.NewFloat64(tableName, "left_anchor_rod_angle")
	_dredgerDataHl.RightAnchorRodAngle = field.NewFloat64(tableName, "right_anchor_rod_angle")
	_dredgerDataHl.MudPump1Speed = field.NewFloat64(tableName, "mud_pump_1_speed")
	_dredgerDataHl.MudPump2Speed = field.NewFloat64(tableName, "mud_pump_2_speed")
	_dredgerDataHl.UnderwaterPumpSpeed = field.NewFloat64(tableName, "underwater_pump_speed")
	_dredgerDataHl.FlowVelocity = field.NewFloat64(tableName, "flow_velocity")
	_dredgerDataHl.Density = field.NewFloat64(tableName, "density")
	_dredgerDataHl.UnderwaterPumpMotorCurrent = field.NewFloat64(tableName, "underwater_pump_motor_current")
	_dredgerDataHl.UnderwaterPumpMotorVoltage = field.NewFloat64(tableName, "underwater_pump_motor_voltage")
	_dredgerDataHl.UnderwaterPumpTorque = field.NewFloat64(tableName, "underwater_pump_torque")
	_dredgerDataHl.UnderwaterPumpMotorSpeed = field.NewFloat64(tableName, "underwater_pump_motor_speed")
	_dredgerDataHl.MudPump2DieselLoad = field.NewFloat64(tableName, "mud_pump_2_diesel_load")
	_dredgerDataHl.MudPump2DieselSpeed = field.NewFloat64(tableName, "mud_pump_2_diesel_speed")
	_dredgerDataHl.MudPump1DieselLoad = field.NewFloat64(tableName, "mud_pump_1_diesel_load")
	_dredgerDataHl.MudPump1DieselSpeed = field.NewFloat64(tableName, "mud_pump_1_diesel_speed")
	_dredgerDataHl.HydraulicPumpDieselLoad = field.NewFloat64(tableName, "hydraulic_pump_diesel_load")
	_dredgerDataHl.HydraulicPumpDieselSpeed = field.NewFloat64(tableName, "hydraulic_pump_diesel_speed")
	_dredgerDataHl.GateValveFlushPressure = field.NewFloat64(tableName, "gate_valve_flush_pressure")
	_dredgerDataHl.CutterBearingFlushPressure = field.NewFloat64(tableName, "cutter_bearing_flush_pressure")
	_dredgerDataHl.TrolleyHydraulicCylinderPressure = field.NewFloat64(tableName, "trolley_hydraulic_cylinder_pressure")
	_dredgerDataHl.SteelPileHydraulicCylinderPressure = field.NewFloat64(tableName, "steel_pile_hydraulic_cylinder_pressure")
	_dredgerDataHl.GateValveSystemPressure = field.NewFloat64(tableName, "gate_valve_system_pressure")
	_dredgerDataHl.RightTransversePressure = field.NewFloat64(tableName, "right_transverse_pressure")
	_dredgerDataHl.LeftTransversePressure = field.NewFloat64(tableName, "left_transverse_pressure")
	_dredgerDataHl.TrolleyTravel = field.NewFloat64(tableName, "trolley_travel")
	_dredgerDataHl.LeftTransverseSpeed = field.NewFloat64(tableName, "left_transverse_speed")
	_dredgerDataHl.RightTransverseSpeed = field.NewFloat64(tableName, "right_transverse_speed")
	_dredgerDataHl.CutterSpeed = field.NewFloat64(tableName, "cutter_speed")
	_dredgerDataHl.MudPump1DischargePressure = field.NewFloat64(tableName, "mud_pump_1_discharge_pressure")
	_dredgerDataHl.MudPump2DischargePressure = field.NewFloat64(tableName, "mud_pump_2_discharge_pressure")
	_dredgerDataHl.UnderwaterPumpDischargePressure = field.NewFloat64(tableName, "underwater_pump_discharge_pressure")
	_dredgerDataHl.UnderwaterPumpSuctionVacuum = field.NewFloat64(tableName, "underwater_pump_suction_vacuum")
	_dredgerDataHl.BridgeAngle = field.NewFloat64(tableName, "bridge_angle")
	_dredgerDataHl.CompassAngle = field.NewFloat64(tableName, "compass_angle")
	_dredgerDataHl.Gps1X = field.NewFloat64(tableName, "gps1_x")
	_dredgerDataHl.Gps1Y = field.NewFloat64(tableName, "gps1_y")
	_dredgerDataHl.Gps1Heading = field.NewFloat64(tableName, "gps1_heading")
	_dredgerDataHl.Gps1Speed = field.NewFloat64(tableName, "gps1_speed")
	_dredgerDataHl.TideLevel = field.NewFloat64(tableName, "tide_level")
	_dredgerDataHl.WaterDensity = field.NewFloat64(tableName, "water_density")
	_dredgerDataHl.FieldSlurryDensity = field.NewFloat64(tableName, "field_slurry_density")
	_dredgerDataHl.TrimAngle = field.NewFloat64(tableName, "trim_angle")
	_dredgerDataHl.PitchAngle = field.NewFloat64(tableName, "pitch_angle")
	_dredgerDataHl.CompassRadian = field.NewFloat64(tableName, "compass_radian")
	_dredgerDataHl.Gps1Latitude = field.NewFloat64(tableName, "gps1_latitude")
	_dredgerDataHl.Gps1Longitude = field.NewFloat64(tableName, "gps1_longitude")
	_dredgerDataHl.EarDraft = field.NewFloat64(tableName, "ear_draft")
	_dredgerDataHl.TransverseSpeed = field.NewFloat64(tableName, "transverse_speed")
	_dredgerDataHl.HourlyOutputRate = field.NewFloat64(tableName, "hourly_output_rate")
	_dredgerDataHl.RotationRadius = field.NewFloat64(tableName, "rotation_radius")
	_dredgerDataHl.CutterX = field.NewFloat64(tableName, "cutter_x")
	_dredgerDataHl.CutterY = field.NewFloat64(tableName, "cutter_y")
	_dredgerDataHl.CurrentShiftOutputRate = field.NewFloat64(tableName, "current_shift_output_rate")
	_dredgerDataHl.CurrentShiftOutput = field.NewFloat64(tableName, "current_shift_output")
	_dredgerDataHl.OutletFlowVelocity = field.NewFloat64(tableName, "outlet_flow_velocity")
	_dredgerDataHl.LeftTransverseTorque = field.NewFloat64(tableName, "left_transverse_torque")
	_dredgerDataHl.CutterTorque = field.NewFloat64(tableName, "cutter_torque")
	_dredgerDataHl.Concentration = field.NewFloat64(tableName, "concentration")
	_dredgerDataHl.FlowRate = field.NewFloat64(tableName, "flow_rate")
	_dredgerDataHl.RightTransverseTorque = field.NewFloat64(tableName, "right_transverse_torque")
	_dredgerDataHl.LeftAnchorWinchSpeed = field.NewFloat64(tableName, "left_anchor_winch_speed")
	_dredgerDataHl.LeftAnchorWinchTorque = field.NewFloat64(tableName, "left_anchor_winch_torque")
	_dredgerDataHl.RightAnchorWinchSpeed = field.NewFloat64(tableName, "right_anchor_winch_speed")
	_dredgerDataHl.RightAnchorWinchTorque = field.NewFloat64(tableName, "right_anchor_winch_torque")
	_dredgerDataHl.LeftSwingWinchSpeed = field.NewFloat64(tableName, "left_swing_winch_speed")
	_dredgerDataHl.LeftSwingWinchTorque = field.NewFloat64(tableName, "left_swing_winch_torque")
	_dredgerDataHl.RightSwingWinchSpeed = field.NewFloat64(tableName, "right_swing_winch_speed")
	_dredgerDataHl.RightSwingWinchTorque = field.NewFloat64(tableName, "right_swing_winch_torque")
	_dredgerDataHl.BridgeWinchSpeed = field.NewFloat64(tableName, "bridge_winch_speed")
	_dredgerDataHl.BridgeWinchTorque = field.NewFloat64(tableName, "bridge_winch_torque")
	_dredgerDataHl.BridgeDepth = field.NewFloat64(tableName, "bridge_depth")
	_dredgerDataHl.CutterCuttingAngle = field.NewFloat64(tableName, "cutter_cutting_angle")
	_dredgerDataHl.TransverseDirection = field.NewInt32(tableName, "transverse_direction")
	_dredgerDataHl.CuttingThickness = field.NewFloat64(tableName, "cutting_thickness")
	_dredgerDataHl.UnderwaterPumpPower = field.NewFloat64(tableName, "underwater_pump_power")
	_dredgerDataHl.MudPump1Power = field.NewFloat64(tableName, "mud_pump_1_power")
	_dredgerDataHl.MudPump2Power = field.NewFloat64(tableName, "mud_pump_2_power")
	_dredgerDataHl.UnderwaterPumpShaftPower = field.NewFloat64(tableName, "underwater_pump_shaft_power")
	_dredgerDataHl.MudPump1ShaftPower = field.NewFloat64(tableName, "mud_pump_1_shaft_power")
	_dredgerDataHl.MudPump2ShaftPower = field.NewFloat64(tableName, "mud_pump_2_shaft_power")
	_dredgerDataHl.UnderwaterPumpEfficiency = field.NewFloat64(tableName, "underwater_pump_efficiency")
	_dredgerDataHl.MudPump1Efficiency = field.NewFloat64(tableName, "mud_pump_1_efficiency")
	_dredgerDataHl.MudPump2Efficiency = field.NewFloat64(tableName, "mud_pump_2_efficiency")
	_dredgerDataHl.PipelineAverageConcentration = field.NewFloat64(tableName, "pipeline_average_concentration")
	_dredgerDataHl.PipelineTotalDamping = field.NewFloat64(tableName, "pipeline_total_damping")
	_dredgerDataHl.DensityForecast = field.NewFloat64(tableName, "density_forecast")
	_dredgerDataHl.ShipDirection = field.NewFloat64(tableName, "ship_direction")
	_dredgerDataHl.Gps1SignalQuality = field.NewFloat64(tableName, "gps1_signal_quality")
	_dredgerDataHl.Gps2SignalQuality = field.NewFloat64(tableName, "gps2_signal_quality")
	_dredgerDataHl.DeckPump1CoverSealPressure = field.NewFloat64(tableName, "deck_pump_1_cover_seal_pressure")
	_dredgerDataHl.DeckPump2CoverSealPressure = field.NewFloat64(tableName, "deck_pump_2_cover_seal_pressure")
	_dredgerDataHl.DeckPump1ShaftSealPressure = field.NewFloat64(tableName, "deck_pump_1_shaft_seal_pressure")
	_dredgerDataHl.DeckPump2ShaftSealPressure = field.NewFloat64(tableName, "deck_pump_2_shaft_seal_pressure")
	_dredgerDataHl.CutterDriveGateValveFlushPressure = field.NewFloat64(tableName, "cutter_drive_gate_valve_flush_pressure")
	_dredgerDataHl.CutterBearingFlushPressureJkt = field.NewFloat64(tableName, "cutter_bearing_flush_pressure_jkt")
	_dredgerDataHl.UnderwaterPumpCoverSealPressure = field.NewFloat64(tableName, "underwater_pump_cover_seal_pressure")
	_dredgerDataHl.UnderwaterPumpShaftSealPressureJkt = field.NewFloat64(tableName, "underwater_pump_shaft_seal_pressure_jkt")
	_dredgerDataHl.DeckPump1GearboxOilTemperature = field.NewFloat64(tableName, "deck_pump_1_gearbox_oil_temperature")
	_dredgerDataHl.DeckPump1GearboxOilPressure = field.NewFloat64(tableName, "deck_pump_1_gearbox_oil_pressure")
	_dredgerDataHl.DeckPump2GearboxOilTemperature = field.NewFloat64(tableName, "deck_pump_2_gearbox_oil_temperature")
	_dredgerDataHl.DeckPump2GearboxOilPressure = field.NewFloat64(tableName, "deck_pump_2_gearbox_oil_pressure")
	_dredgerDataHl.CutterDriveGearboxOilTemperature = field.NewFloat64(tableName, "cutter_drive_gearbox_oil_temperature")
	_dredgerDataHl.CutterDriveGearboxOilPressure = field.NewFloat64(tableName, "cutter_drive_gearbox_oil_pressure")
	_dredgerDataHl.CutterDriveGearboxOilSaturation = field.NewFloat64(tableName, "cutter_drive_gearbox_oil_saturation")
	_dredgerDataHl.UnderwaterPumpGearboxOilTemperature = field.NewFloat64(tableName, "underwater_pump_gearbox_oil_temperature")
	_dredgerDataHl.UnderwaterPumpGearboxOilPressure = field.NewFloat64(tableName, "underwater_pump_gearbox_oil_pressure")
	_dredgerDataHl.UnderwaterPumpGearboxOilSaturation = field.NewFloat64(tableName, "underwater_pump_gearbox_oil_saturation")
	_dredgerDataHl.FuelTank40Level = field.NewFloat64(tableName, "fuel_tank_40_level")
	_dredgerDataHl.MerFuelDailyTankLevel = field.NewFloat64(tableName, "mer_fuel_daily_tank_level")
	_dredgerDataHl.FuelTank3Level = field.NewFloat64(tableName, "fuel_tank_3_level")
	_dredgerDataHl.LubricatingOilTank5Level = field.NewFloat64(tableName, "lubricating_oil_tank_5_level")
	_dredgerDataHl.HydraulicOilTank7Level = field.NewFloat64(tableName, "hydraulic_oil_tank_7_level")
	_dredgerDataHl.AuxiliaryFuelDailyTankLevel = field.NewFloat64(tableName, "auxiliary_fuel_daily_tank_level")
	_dredgerDataHl.FuelTank13Level = field.NewFloat64(tableName, "fuel_tank_13_level")
	_dredgerDataHl.FuelTank3ALevel = field.NewFloat64(tableName, "fuel_tank_3a_level")
	_dredgerDataHl.FuelTank4Level = field.NewFloat64(tableName, "fuel_tank_4_level")
	_dredgerDataHl.SewageTank6Level = field.NewFloat64(tableName, "sewage_tank_6_level")
	_dredgerDataHl.FreshwaterTank8Level = field.NewFloat64(tableName, "freshwater_tank_8_level")
	_dredgerDataHl.DirtyOilTank11Level = field.NewFloat64(tableName, "dirty_oil_tank_11_level")
	_dredgerDataHl.FuelTank12Level = field.NewFloat64(tableName, "fuel_tank_12_level")
	_dredgerDataHl.FreshwaterTank26Level = field.NewFloat64(tableName, "freshwater_tank_26_level")
	_dredgerDataHl.FuelTank4ALevel = field.NewFloat64(tableName, "fuel_tank_4a_level")

	_dredgerDataHl.fillFieldMap()

	return _dredgerDataHl
}

// dredgerDataHl 华安龙绞吸式挖泥船施工数据表
type dredgerDataHl struct {
	dredgerDataHlDo

	ALL                                 field.Asterisk
	ID                                  field.Int64   // 主键id
	ShipName                            field.String  // 船名
	RecordTime                          field.Int64   // 时间
	LeftEarDraft                        field.Float64 // 左耳轴吃水(m)
	UnderwaterPumpSuctionSealPressure   field.Float64 // 水下泵吸入端封水压力(bar)
	UnderwaterPumpShaftSealPressure     field.Float64 // 水下泵轴端封水压力(bar)
	MudPump1ShaftSealPressure           field.Float64 // 1#泥泵轴端封水压力(bar)
	MudPump1SuctionSealPressure         field.Float64 // 1#泥泵吸入端封水压力(bar)
	MudPump2SuctionSealPressure         field.Float64 // 2#泥泵吸入端封水压力(bar)
	MudPump2ShaftSealPressure           field.Float64 // 2#泥泵轴端封水压力(bar)
	RightEarDraft                       field.Float64 // 右耳轴吃水(m)
	LeftAnchorRodAngle                  field.Float64 // 左抛锚杆角度传感器(°)
	RightAnchorRodAngle                 field.Float64 // 右抛锚杆角度传感器(°)
	MudPump1Speed                       field.Float64 // 1#泥泵转速(rpm)
	MudPump2Speed                       field.Float64 // 2#泥泵转速(rpm)
	UnderwaterPumpSpeed                 field.Float64 // 水下泵转速(rpm)
	FlowVelocity                        field.Float64 // 流速(m/s)
	Density                             field.Float64 // 密度(t/m3)
	UnderwaterPumpMotorCurrent          field.Float64 // 水下泵电机电流(A)
	UnderwaterPumpMotorVoltage          field.Float64 // 水下泵电机电压(V)
	UnderwaterPumpTorque                field.Float64 // 水下泵扭矩(KN)
	UnderwaterPumpMotorSpeed            field.Float64 // 水下泵电机转速(rpm)
	MudPump2DieselLoad                  field.Float64 // 2#泥泵柴油机负荷(mm)
	MudPump2DieselSpeed                 field.Float64 // 2#泥泵柴油机转速(rpm)
	MudPump1DieselLoad                  field.Float64 // 1#泥泵柴油机负荷(mm)
	MudPump1DieselSpeed                 field.Float64 // 1#泥泵柴油机转速(rpm)
	HydraulicPumpDieselLoad             field.Float64 // 液压泵柴油机负荷(mm)
	HydraulicPumpDieselSpeed            field.Float64 // 液压泵柴油机转速(rpm)
	GateValveFlushPressure              field.Float64 // 闸阀冲洗压力(bar)
	CutterBearingFlushPressure          field.Float64 // 绞刀轴承冲水压力(bar)
	TrolleyHydraulicCylinderPressure    field.Float64 // 台车液压油缸压力(bar)
	SteelPileHydraulicCylinderPressure  field.Float64 // 钢桩液压油缸压力(bar)
	GateValveSystemPressure             field.Float64 // 闸阀系统压力(bar)
	RightTransversePressure             field.Float64 // 压力传感器（右横移压力）(bar)
	LeftTransversePressure              field.Float64 // 压力传感器（左横移压力）(bar)
	TrolleyTravel                       field.Float64 // 台车行程(m)
	LeftTransverseSpeed                 field.Float64 // 左横移速度(m/min)
	RightTransverseSpeed                field.Float64 // 右横移速度(m/min)
	CutterSpeed                         field.Float64 // 绞刀转速(rpm)
	MudPump1DischargePressure           field.Float64 // 1#泥泵排出压力(bar)
	MudPump2DischargePressure           field.Float64 // 2#泥泵排出压力(bar)
	UnderwaterPumpDischargePressure     field.Float64 // 水下泵排出压力(bar)
	UnderwaterPumpSuctionVacuum         field.Float64 // 水下泵吸入真空(bar)
	BridgeAngle                         field.Float64 // 桥架角度(°)
	CompassAngle                        field.Float64 // 罗经角度(°)
	Gps1X                               field.Float64 // GPS1_X(°)
	Gps1Y                               field.Float64 // GPS1_Y(°)
	Gps1Heading                         field.Float64 // GPS1航向(°)
	Gps1Speed                           field.Float64 // GPS1航速(kn)
	TideLevel                           field.Float64 // 潮位(m)
	WaterDensity                        field.Float64 // 水密度(kg/m3)
	FieldSlurryDensity                  field.Float64 // 现场泥浆比重(null)
	TrimAngle                           field.Float64 // 横倾角度(°)
	PitchAngle                          field.Float64 // 纵倾角度(°)
	CompassRadian                       field.Float64 // 罗经弧度(null)
	Gps1Latitude                        field.Float64 // GPS1_纬度(°)
	Gps1Longitude                       field.Float64 // GPS1_经度(°)
	EarDraft                            field.Float64 // 耳轴吃水(m)
	TransverseSpeed                     field.Float64 // 横移速度(m/min)
	HourlyOutputRate                    field.Float64 // 小时产量率(m3/h)
	RotationRadius                      field.Float64 // 旋转半径(m)
	CutterX                             field.Float64 // 绞刀x(m)
	CutterY                             field.Float64 // 绞刀y(m)
	CurrentShiftOutputRate              field.Float64 // 当前班产量率(m3/h)
	CurrentShiftOutput                  field.Float64 // 当前班产量(m3)
	OutletFlowVelocity                  field.Float64 // 出口流速(m/s)
	LeftTransverseTorque                field.Float64 // 左横移扭矩(KN)
	CutterTorque                        field.Float64 // 绞刀扭矩(KN)
	Concentration                       field.Float64 // 浓度(%)
	FlowRate                            field.Float64 // 流量(m3/h)
	RightTransverseTorque               field.Float64 // 右横移扭矩(KN)
	LeftAnchorWinchSpeed                field.Float64 // 左起锚绞车速度(m/min)
	LeftAnchorWinchTorque               field.Float64 // 左起锚绞车扭矩(KN)
	RightAnchorWinchSpeed               field.Float64 // 右起锚绞车速度(m/min)
	RightAnchorWinchTorque              field.Float64 // 右起锚绞车扭矩(KN)
	LeftSwingWinchSpeed                 field.Float64 // 左回转绞车速度(m/min)
	LeftSwingWinchTorque                field.Float64 // 左回转绞车扭矩(KN)
	RightSwingWinchSpeed                field.Float64 // 右回转绞车速度(m/min)
	RightSwingWinchTorque               field.Float64 // 右回转绞车扭矩(KN)
	BridgeWinchSpeed                    field.Float64 // 起桥绞车速度(m/min)
	BridgeWinchTorque                   field.Float64 // 起桥绞车扭矩(KN)
	BridgeDepth                         field.Float64 // 桥架深度(m)
	CutterCuttingAngle                  field.Float64 // 绞刀切削角(°)
	TransverseDirection                 field.Int32   // 横移方向(null)
	CuttingThickness                    field.Float64 // 切削厚度(m)
	UnderwaterPumpPower                 field.Float64 // 水下泵功率(kw)
	MudPump1Power                       field.Float64 // 1#泥泵功率(kw)
	MudPump2Power                       field.Float64 // 2#泥泵功率(kw)
	UnderwaterPumpShaftPower            field.Float64 // 水下泵轴端驱动功率(kw)
	MudPump1ShaftPower                  field.Float64 // 1#泥泵轴端驱动功率(kw)
	MudPump2ShaftPower                  field.Float64 // 2#泥泵轴端驱动功率(kw)
	UnderwaterPumpEfficiency            field.Float64 // 水下泵泵效(null)
	MudPump1Efficiency                  field.Float64 // 1#泥泵泵效(null)
	MudPump2Efficiency                  field.Float64 // 2#泥泵泵效(null)
	PipelineAverageConcentration        field.Float64 // 管路平均浓度(%)
	PipelineTotalDamping                field.Float64 // 管路总阻尼(null)
	DensityForecast                     field.Float64 // 密度预报值(t/m3)
	ShipDirection                       field.Float64 // 船体方向(null)
	Gps1SignalQuality                   field.Float64 // 1#GPS信号质量(null)
	Gps2SignalQuality                   field.Float64 // 2#GPS信号质量(null)
	DeckPump1CoverSealPressure          field.Float64 // [JKT]1#甲板泵盖端封水压力(bar)
	DeckPump2CoverSealPressure          field.Float64 // [JKT]2#甲板泵盖端封水压力(bar)
	DeckPump1ShaftSealPressure          field.Float64 // [JKT]1#甲板泵轴端封水压力(bar)
	DeckPump2ShaftSealPressure          field.Float64 // [JKT]2#甲板泵轴端封水压力(bar)
	CutterDriveGateValveFlushPressure   field.Float64 // [JKT]绞刀驱动闸阀冲水压力(bar)
	CutterBearingFlushPressureJkt       field.Float64 // [JKT]绞刀轴承冲水压力(bar)
	UnderwaterPumpCoverSealPressure     field.Float64 // [JKT]水下泵盖端封水压力(bar)
	UnderwaterPumpShaftSealPressureJkt  field.Float64 // [JKT]水下泵轴端封水压力(bar)
	DeckPump1GearboxOilTemperature      field.Float64 // [JKT]1#甲板泵齿轮箱滑油温度(℃)
	DeckPump1GearboxOilPressure         field.Float64 // [JKT]1#甲板泵齿轮箱滑油压力(bar)
	DeckPump2GearboxOilTemperature      field.Float64 // [JKT]2#甲板泵齿轮箱滑油温度(℃)
	DeckPump2GearboxOilPressure         field.Float64 // [JKT]2#甲板泵齿轮箱滑油压力(bar)
	CutterDriveGearboxOilTemperature    field.Float64 // [JKT]绞刀驱动齿轮箱滑油温度(℃)
	CutterDriveGearboxOilPressure       field.Float64 // [JKT]绞刀驱动齿轮箱滑油压力(bar)
	CutterDriveGearboxOilSaturation     field.Float64 // [JKT]绞刀驱动齿轮箱滑油进水饱和度(%)
	UnderwaterPumpGearboxOilTemperature field.Float64 // [JKT]水下泵齿轮箱滑油温度(℃)
	UnderwaterPumpGearboxOilPressure    field.Float64 // [JKT]水下泵齿轮箱滑油压力(bar)
	UnderwaterPumpGearboxOilSaturation  field.Float64 // [JKT]水下泵齿轮箱滑油进水饱和度(%)
	FuelTank40Level                     field.Float64 // [BPJ]燃油舱40液位状态显示(m)
	MerFuelDailyTankLevel               field.Float64 // [BC]MER燃油日用柜液位(m)
	FuelTank3Level                      field.Float64 // [SBCL]燃油舱3液位(m)
	LubricatingOilTank5Level            field.Float64 // [SBCL]滑油储存舱5液位(m)
	HydraulicOilTank7Level              field.Float64 // [SBCL]液压油储存舱7液位(m)
	AuxiliaryFuelDailyTankLevel         field.Float64 // [SBCL]辅机舱燃油日用柜液位(m)
	FuelTank13Level                     field.Float64 // [SBCL]燃油舱13液位(m)
	FuelTank3ALevel                     field.Float64 // [SBCL]燃油舱3A液位状态显示(m)
	FuelTank4Level                      field.Float64 // [SBCR]燃油舱4液位(m)
	SewageTank6Level                    field.Float64 // [SBCR]污水舱6液位(m)
	FreshwaterTank8Level                field.Float64 // [SBCR]淡水舱8液位(m)
	DirtyOilTank11Level                 field.Float64 // [SBCR]污油舱11液位(m)
	FuelTank12Level                     field.Float64 // [SBCR]燃油舱12液位(m)
	FreshwaterTank26Level               field.Float64 // [SBCR]淡水舱26液位(m)
	FuelTank4ALevel                     field.Float64 // [SBCR]燃油舱4A液位显示状态(m)

	fieldMap map[string]field.Expr
}

func (d dredgerDataHl) Table(newTableName string) *dredgerDataHl {
	d.dredgerDataHlDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dredgerDataHl) As(alias string) *dredgerDataHl {
	d.dredgerDataHlDo.DO = *(d.dredgerDataHlDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dredgerDataHl) updateTableName(table string) *dredgerDataHl {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.ShipName = field.NewString(table, "ship_name")
	d.RecordTime = field.NewInt64(table, "record_time")
	d.LeftEarDraft = field.NewFloat64(table, "left_ear_draft")
	d.UnderwaterPumpSuctionSealPressure = field.NewFloat64(table, "underwater_pump_suction_seal_pressure")
	d.UnderwaterPumpShaftSealPressure = field.NewFloat64(table, "underwater_pump_shaft_seal_pressure")
	d.MudPump1ShaftSealPressure = field.NewFloat64(table, "mud_pump_1_shaft_seal_pressure")
	d.MudPump1SuctionSealPressure = field.NewFloat64(table, "mud_pump_1_suction_seal_pressure")
	d.MudPump2SuctionSealPressure = field.NewFloat64(table, "mud_pump_2_suction_seal_pressure")
	d.MudPump2ShaftSealPressure = field.NewFloat64(table, "mud_pump_2_shaft_seal_pressure")
	d.RightEarDraft = field.NewFloat64(table, "right_ear_draft")
	d.LeftAnchorRodAngle = field.NewFloat64(table, "left_anchor_rod_angle")
	d.RightAnchorRodAngle = field.NewFloat64(table, "right_anchor_rod_angle")
	d.MudPump1Speed = field.NewFloat64(table, "mud_pump_1_speed")
	d.MudPump2Speed = field.NewFloat64(table, "mud_pump_2_speed")
	d.UnderwaterPumpSpeed = field.NewFloat64(table, "underwater_pump_speed")
	d.FlowVelocity = field.NewFloat64(table, "flow_velocity")
	d.Density = field.NewFloat64(table, "density")
	d.UnderwaterPumpMotorCurrent = field.NewFloat64(table, "underwater_pump_motor_current")
	d.UnderwaterPumpMotorVoltage = field.NewFloat64(table, "underwater_pump_motor_voltage")
	d.UnderwaterPumpTorque = field.NewFloat64(table, "underwater_pump_torque")
	d.UnderwaterPumpMotorSpeed = field.NewFloat64(table, "underwater_pump_motor_speed")
	d.MudPump2DieselLoad = field.NewFloat64(table, "mud_pump_2_diesel_load")
	d.MudPump2DieselSpeed = field.NewFloat64(table, "mud_pump_2_diesel_speed")
	d.MudPump1DieselLoad = field.NewFloat64(table, "mud_pump_1_diesel_load")
	d.MudPump1DieselSpeed = field.NewFloat64(table, "mud_pump_1_diesel_speed")
	d.HydraulicPumpDieselLoad = field.NewFloat64(table, "hydraulic_pump_diesel_load")
	d.HydraulicPumpDieselSpeed = field.NewFloat64(table, "hydraulic_pump_diesel_speed")
	d.GateValveFlushPressure = field.NewFloat64(table, "gate_valve_flush_pressure")
	d.CutterBearingFlushPressure = field.NewFloat64(table, "cutter_bearing_flush_pressure")
	d.TrolleyHydraulicCylinderPressure = field.NewFloat64(table, "trolley_hydraulic_cylinder_pressure")
	d.SteelPileHydraulicCylinderPressure = field.NewFloat64(table, "steel_pile_hydraulic_cylinder_pressure")
	d.GateValveSystemPressure = field.NewFloat64(table, "gate_valve_system_pressure")
	d.RightTransversePressure = field.NewFloat64(table, "right_transverse_pressure")
	d.LeftTransversePressure = field.NewFloat64(table, "left_transverse_pressure")
	d.TrolleyTravel = field.NewFloat64(table, "trolley_travel")
	d.LeftTransverseSpeed = field.NewFloat64(table, "left_transverse_speed")
	d.RightTransverseSpeed = field.NewFloat64(table, "right_transverse_speed")
	d.CutterSpeed = field.NewFloat64(table, "cutter_speed")
	d.MudPump1DischargePressure = field.NewFloat64(table, "mud_pump_1_discharge_pressure")
	d.MudPump2DischargePressure = field.NewFloat64(table, "mud_pump_2_discharge_pressure")
	d.UnderwaterPumpDischargePressure = field.NewFloat64(table, "underwater_pump_discharge_pressure")
	d.UnderwaterPumpSuctionVacuum = field.NewFloat64(table, "underwater_pump_suction_vacuum")
	d.BridgeAngle = field.NewFloat64(table, "bridge_angle")
	d.CompassAngle = field.NewFloat64(table, "compass_angle")
	d.Gps1X = field.NewFloat64(table, "gps1_x")
	d.Gps1Y = field.NewFloat64(table, "gps1_y")
	d.Gps1Heading = field.NewFloat64(table, "gps1_heading")
	d.Gps1Speed = field.NewFloat64(table, "gps1_speed")
	d.TideLevel = field.NewFloat64(table, "tide_level")
	d.WaterDensity = field.NewFloat64(table, "water_density")
	d.FieldSlurryDensity = field.NewFloat64(table, "field_slurry_density")
	d.TrimAngle = field.NewFloat64(table, "trim_angle")
	d.PitchAngle = field.NewFloat64(table, "pitch_angle")
	d.CompassRadian = field.NewFloat64(table, "compass_radian")
	d.Gps1Latitude = field.NewFloat64(table, "gps1_latitude")
	d.Gps1Longitude = field.NewFloat64(table, "gps1_longitude")
	d.EarDraft = field.NewFloat64(table, "ear_draft")
	d.TransverseSpeed = field.NewFloat64(table, "transverse_speed")
	d.HourlyOutputRate = field.NewFloat64(table, "hourly_output_rate")
	d.RotationRadius = field.NewFloat64(table, "rotation_radius")
	d.CutterX = field.NewFloat64(table, "cutter_x")
	d.CutterY = field.NewFloat64(table, "cutter_y")
	d.CurrentShiftOutputRate = field.NewFloat64(table, "current_shift_output_rate")
	d.CurrentShiftOutput = field.NewFloat64(table, "current_shift_output")
	d.OutletFlowVelocity = field.NewFloat64(table, "outlet_flow_velocity")
	d.LeftTransverseTorque = field.NewFloat64(table, "left_transverse_torque")
	d.CutterTorque = field.NewFloat64(table, "cutter_torque")
	d.Concentration = field.NewFloat64(table, "concentration")
	d.FlowRate = field.NewFloat64(table, "flow_rate")
	d.RightTransverseTorque = field.NewFloat64(table, "right_transverse_torque")
	d.LeftAnchorWinchSpeed = field.NewFloat64(table, "left_anchor_winch_speed")
	d.LeftAnchorWinchTorque = field.NewFloat64(table, "left_anchor_winch_torque")
	d.RightAnchorWinchSpeed = field.NewFloat64(table, "right_anchor_winch_speed")
	d.RightAnchorWinchTorque = field.NewFloat64(table, "right_anchor_winch_torque")
	d.LeftSwingWinchSpeed = field.NewFloat64(table, "left_swing_winch_speed")
	d.LeftSwingWinchTorque = field.NewFloat64(table, "left_swing_winch_torque")
	d.RightSwingWinchSpeed = field.NewFloat64(table, "right_swing_winch_speed")
	d.RightSwingWinchTorque = field.NewFloat64(table, "right_swing_winch_torque")
	d.BridgeWinchSpeed = field.NewFloat64(table, "bridge_winch_speed")
	d.BridgeWinchTorque = field.NewFloat64(table, "bridge_winch_torque")
	d.BridgeDepth = field.NewFloat64(table, "bridge_depth")
	d.CutterCuttingAngle = field.NewFloat64(table, "cutter_cutting_angle")
	d.TransverseDirection = field.NewInt32(table, "transverse_direction")
	d.CuttingThickness = field.NewFloat64(table, "cutting_thickness")
	d.UnderwaterPumpPower = field.NewFloat64(table, "underwater_pump_power")
	d.MudPump1Power = field.NewFloat64(table, "mud_pump_1_power")
	d.MudPump2Power = field.NewFloat64(table, "mud_pump_2_power")
	d.UnderwaterPumpShaftPower = field.NewFloat64(table, "underwater_pump_shaft_power")
	d.MudPump1ShaftPower = field.NewFloat64(table, "mud_pump_1_shaft_power")
	d.MudPump2ShaftPower = field.NewFloat64(table, "mud_pump_2_shaft_power")
	d.UnderwaterPumpEfficiency = field.NewFloat64(table, "underwater_pump_efficiency")
	d.MudPump1Efficiency = field.NewFloat64(table, "mud_pump_1_efficiency")
	d.MudPump2Efficiency = field.NewFloat64(table, "mud_pump_2_efficiency")
	d.PipelineAverageConcentration = field.NewFloat64(table, "pipeline_average_concentration")
	d.PipelineTotalDamping = field.NewFloat64(table, "pipeline_total_damping")
	d.DensityForecast = field.NewFloat64(table, "density_forecast")
	d.ShipDirection = field.NewFloat64(table, "ship_direction")
	d.Gps1SignalQuality = field.NewFloat64(table, "gps1_signal_quality")
	d.Gps2SignalQuality = field.NewFloat64(table, "gps2_signal_quality")
	d.DeckPump1CoverSealPressure = field.NewFloat64(table, "deck_pump_1_cover_seal_pressure")
	d.DeckPump2CoverSealPressure = field.NewFloat64(table, "deck_pump_2_cover_seal_pressure")
	d.DeckPump1ShaftSealPressure = field.NewFloat64(table, "deck_pump_1_shaft_seal_pressure")
	d.DeckPump2ShaftSealPressure = field.NewFloat64(table, "deck_pump_2_shaft_seal_pressure")
	d.CutterDriveGateValveFlushPressure = field.NewFloat64(table, "cutter_drive_gate_valve_flush_pressure")
	d.CutterBearingFlushPressureJkt = field.NewFloat64(table, "cutter_bearing_flush_pressure_jkt")
	d.UnderwaterPumpCoverSealPressure = field.NewFloat64(table, "underwater_pump_cover_seal_pressure")
	d.UnderwaterPumpShaftSealPressureJkt = field.NewFloat64(table, "underwater_pump_shaft_seal_pressure_jkt")
	d.DeckPump1GearboxOilTemperature = field.NewFloat64(table, "deck_pump_1_gearbox_oil_temperature")
	d.DeckPump1GearboxOilPressure = field.NewFloat64(table, "deck_pump_1_gearbox_oil_pressure")
	d.DeckPump2GearboxOilTemperature = field.NewFloat64(table, "deck_pump_2_gearbox_oil_temperature")
	d.DeckPump2GearboxOilPressure = field.NewFloat64(table, "deck_pump_2_gearbox_oil_pressure")
	d.CutterDriveGearboxOilTemperature = field.NewFloat64(table, "cutter_drive_gearbox_oil_temperature")
	d.CutterDriveGearboxOilPressure = field.NewFloat64(table, "cutter_drive_gearbox_oil_pressure")
	d.CutterDriveGearboxOilSaturation = field.NewFloat64(table, "cutter_drive_gearbox_oil_saturation")
	d.UnderwaterPumpGearboxOilTemperature = field.NewFloat64(table, "underwater_pump_gearbox_oil_temperature")
	d.UnderwaterPumpGearboxOilPressure = field.NewFloat64(table, "underwater_pump_gearbox_oil_pressure")
	d.UnderwaterPumpGearboxOilSaturation = field.NewFloat64(table, "underwater_pump_gearbox_oil_saturation")
	d.FuelTank40Level = field.NewFloat64(table, "fuel_tank_40_level")
	d.MerFuelDailyTankLevel = field.NewFloat64(table, "mer_fuel_daily_tank_level")
	d.FuelTank3Level = field.NewFloat64(table, "fuel_tank_3_level")
	d.LubricatingOilTank5Level = field.NewFloat64(table, "lubricating_oil_tank_5_level")
	d.HydraulicOilTank7Level = field.NewFloat64(table, "hydraulic_oil_tank_7_level")
	d.AuxiliaryFuelDailyTankLevel = field.NewFloat64(table, "auxiliary_fuel_daily_tank_level")
	d.FuelTank13Level = field.NewFloat64(table, "fuel_tank_13_level")
	d.FuelTank3ALevel = field.NewFloat64(table, "fuel_tank_3a_level")
	d.FuelTank4Level = field.NewFloat64(table, "fuel_tank_4_level")
	d.SewageTank6Level = field.NewFloat64(table, "sewage_tank_6_level")
	d.FreshwaterTank8Level = field.NewFloat64(table, "freshwater_tank_8_level")
	d.DirtyOilTank11Level = field.NewFloat64(table, "dirty_oil_tank_11_level")
	d.FuelTank12Level = field.NewFloat64(table, "fuel_tank_12_level")
	d.FreshwaterTank26Level = field.NewFloat64(table, "freshwater_tank_26_level")
	d.FuelTank4ALevel = field.NewFloat64(table, "fuel_tank_4a_level")

	d.fillFieldMap()

	return d
}

func (d *dredgerDataHl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dredgerDataHl) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 133)
	d.fieldMap["id"] = d.ID
	d.fieldMap["ship_name"] = d.ShipName
	d.fieldMap["record_time"] = d.RecordTime
	d.fieldMap["left_ear_draft"] = d.LeftEarDraft
	d.fieldMap["underwater_pump_suction_seal_pressure"] = d.UnderwaterPumpSuctionSealPressure
	d.fieldMap["underwater_pump_shaft_seal_pressure"] = d.UnderwaterPumpShaftSealPressure
	d.fieldMap["mud_pump_1_shaft_seal_pressure"] = d.MudPump1ShaftSealPressure
	d.fieldMap["mud_pump_1_suction_seal_pressure"] = d.MudPump1SuctionSealPressure
	d.fieldMap["mud_pump_2_suction_seal_pressure"] = d.MudPump2SuctionSealPressure
	d.fieldMap["mud_pump_2_shaft_seal_pressure"] = d.MudPump2ShaftSealPressure
	d.fieldMap["right_ear_draft"] = d.RightEarDraft
	d.fieldMap["left_anchor_rod_angle"] = d.LeftAnchorRodAngle
	d.fieldMap["right_anchor_rod_angle"] = d.RightAnchorRodAngle
	d.fieldMap["mud_pump_1_speed"] = d.MudPump1Speed
	d.fieldMap["mud_pump_2_speed"] = d.MudPump2Speed
	d.fieldMap["underwater_pump_speed"] = d.UnderwaterPumpSpeed
	d.fieldMap["flow_velocity"] = d.FlowVelocity
	d.fieldMap["density"] = d.Density
	d.fieldMap["underwater_pump_motor_current"] = d.UnderwaterPumpMotorCurrent
	d.fieldMap["underwater_pump_motor_voltage"] = d.UnderwaterPumpMotorVoltage
	d.fieldMap["underwater_pump_torque"] = d.UnderwaterPumpTorque
	d.fieldMap["underwater_pump_motor_speed"] = d.UnderwaterPumpMotorSpeed
	d.fieldMap["mud_pump_2_diesel_load"] = d.MudPump2DieselLoad
	d.fieldMap["mud_pump_2_diesel_speed"] = d.MudPump2DieselSpeed
	d.fieldMap["mud_pump_1_diesel_load"] = d.MudPump1DieselLoad
	d.fieldMap["mud_pump_1_diesel_speed"] = d.MudPump1DieselSpeed
	d.fieldMap["hydraulic_pump_diesel_load"] = d.HydraulicPumpDieselLoad
	d.fieldMap["hydraulic_pump_diesel_speed"] = d.HydraulicPumpDieselSpeed
	d.fieldMap["gate_valve_flush_pressure"] = d.GateValveFlushPressure
	d.fieldMap["cutter_bearing_flush_pressure"] = d.CutterBearingFlushPressure
	d.fieldMap["trolley_hydraulic_cylinder_pressure"] = d.TrolleyHydraulicCylinderPressure
	d.fieldMap["steel_pile_hydraulic_cylinder_pressure"] = d.SteelPileHydraulicCylinderPressure
	d.fieldMap["gate_valve_system_pressure"] = d.GateValveSystemPressure
	d.fieldMap["right_transverse_pressure"] = d.RightTransversePressure
	d.fieldMap["left_transverse_pressure"] = d.LeftTransversePressure
	d.fieldMap["trolley_travel"] = d.TrolleyTravel
	d.fieldMap["left_transverse_speed"] = d.LeftTransverseSpeed
	d.fieldMap["right_transverse_speed"] = d.RightTransverseSpeed
	d.fieldMap["cutter_speed"] = d.CutterSpeed
	d.fieldMap["mud_pump_1_discharge_pressure"] = d.MudPump1DischargePressure
	d.fieldMap["mud_pump_2_discharge_pressure"] = d.MudPump2DischargePressure
	d.fieldMap["underwater_pump_discharge_pressure"] = d.UnderwaterPumpDischargePressure
	d.fieldMap["underwater_pump_suction_vacuum"] = d.UnderwaterPumpSuctionVacuum
	d.fieldMap["bridge_angle"] = d.BridgeAngle
	d.fieldMap["compass_angle"] = d.CompassAngle
	d.fieldMap["gps1_x"] = d.Gps1X
	d.fieldMap["gps1_y"] = d.Gps1Y
	d.fieldMap["gps1_heading"] = d.Gps1Heading
	d.fieldMap["gps1_speed"] = d.Gps1Speed
	d.fieldMap["tide_level"] = d.TideLevel
	d.fieldMap["water_density"] = d.WaterDensity
	d.fieldMap["field_slurry_density"] = d.FieldSlurryDensity
	d.fieldMap["trim_angle"] = d.TrimAngle
	d.fieldMap["pitch_angle"] = d.PitchAngle
	d.fieldMap["compass_radian"] = d.CompassRadian
	d.fieldMap["gps1_latitude"] = d.Gps1Latitude
	d.fieldMap["gps1_longitude"] = d.Gps1Longitude
	d.fieldMap["ear_draft"] = d.EarDraft
	d.fieldMap["transverse_speed"] = d.TransverseSpeed
	d.fieldMap["hourly_output_rate"] = d.HourlyOutputRate
	d.fieldMap["rotation_radius"] = d.RotationRadius
	d.fieldMap["cutter_x"] = d.CutterX
	d.fieldMap["cutter_y"] = d.CutterY
	d.fieldMap["current_shift_output_rate"] = d.CurrentShiftOutputRate
	d.fieldMap["current_shift_output"] = d.CurrentShiftOutput
	d.fieldMap["outlet_flow_velocity"] = d.OutletFlowVelocity
	d.fieldMap["left_transverse_torque"] = d.LeftTransverseTorque
	d.fieldMap["cutter_torque"] = d.CutterTorque
	d.fieldMap["concentration"] = d.Concentration
	d.fieldMap["flow_rate"] = d.FlowRate
	d.fieldMap["right_transverse_torque"] = d.RightTransverseTorque
	d.fieldMap["left_anchor_winch_speed"] = d.LeftAnchorWinchSpeed
	d.fieldMap["left_anchor_winch_torque"] = d.LeftAnchorWinchTorque
	d.fieldMap["right_anchor_winch_speed"] = d.RightAnchorWinchSpeed
	d.fieldMap["right_anchor_winch_torque"] = d.RightAnchorWinchTorque
	d.fieldMap["left_swing_winch_speed"] = d.LeftSwingWinchSpeed
	d.fieldMap["left_swing_winch_torque"] = d.LeftSwingWinchTorque
	d.fieldMap["right_swing_winch_speed"] = d.RightSwingWinchSpeed
	d.fieldMap["right_swing_winch_torque"] = d.RightSwingWinchTorque
	d.fieldMap["bridge_winch_speed"] = d.BridgeWinchSpeed
	d.fieldMap["bridge_winch_torque"] = d.BridgeWinchTorque
	d.fieldMap["bridge_depth"] = d.BridgeDepth
	d.fieldMap["cutter_cutting_angle"] = d.CutterCuttingAngle
	d.fieldMap["transverse_direction"] = d.TransverseDirection
	d.fieldMap["cutting_thickness"] = d.CuttingThickness
	d.fieldMap["underwater_pump_power"] = d.UnderwaterPumpPower
	d.fieldMap["mud_pump_1_power"] = d.MudPump1Power
	d.fieldMap["mud_pump_2_power"] = d.MudPump2Power
	d.fieldMap["underwater_pump_shaft_power"] = d.UnderwaterPumpShaftPower
	d.fieldMap["mud_pump_1_shaft_power"] = d.MudPump1ShaftPower
	d.fieldMap["mud_pump_2_shaft_power"] = d.MudPump2ShaftPower
	d.fieldMap["underwater_pump_efficiency"] = d.UnderwaterPumpEfficiency
	d.fieldMap["mud_pump_1_efficiency"] = d.MudPump1Efficiency
	d.fieldMap["mud_pump_2_efficiency"] = d.MudPump2Efficiency
	d.fieldMap["pipeline_average_concentration"] = d.PipelineAverageConcentration
	d.fieldMap["pipeline_total_damping"] = d.PipelineTotalDamping
	d.fieldMap["density_forecast"] = d.DensityForecast
	d.fieldMap["ship_direction"] = d.ShipDirection
	d.fieldMap["gps1_signal_quality"] = d.Gps1SignalQuality
	d.fieldMap["gps2_signal_quality"] = d.Gps2SignalQuality
	d.fieldMap["deck_pump_1_cover_seal_pressure"] = d.DeckPump1CoverSealPressure
	d.fieldMap["deck_pump_2_cover_seal_pressure"] = d.DeckPump2CoverSealPressure
	d.fieldMap["deck_pump_1_shaft_seal_pressure"] = d.DeckPump1ShaftSealPressure
	d.fieldMap["deck_pump_2_shaft_seal_pressure"] = d.DeckPump2ShaftSealPressure
	d.fieldMap["cutter_drive_gate_valve_flush_pressure"] = d.CutterDriveGateValveFlushPressure
	d.fieldMap["cutter_bearing_flush_pressure_jkt"] = d.CutterBearingFlushPressureJkt
	d.fieldMap["underwater_pump_cover_seal_pressure"] = d.UnderwaterPumpCoverSealPressure
	d.fieldMap["underwater_pump_shaft_seal_pressure_jkt"] = d.UnderwaterPumpShaftSealPressureJkt
	d.fieldMap["deck_pump_1_gearbox_oil_temperature"] = d.DeckPump1GearboxOilTemperature
	d.fieldMap["deck_pump_1_gearbox_oil_pressure"] = d.DeckPump1GearboxOilPressure
	d.fieldMap["deck_pump_2_gearbox_oil_temperature"] = d.DeckPump2GearboxOilTemperature
	d.fieldMap["deck_pump_2_gearbox_oil_pressure"] = d.DeckPump2GearboxOilPressure
	d.fieldMap["cutter_drive_gearbox_oil_temperature"] = d.CutterDriveGearboxOilTemperature
	d.fieldMap["cutter_drive_gearbox_oil_pressure"] = d.CutterDriveGearboxOilPressure
	d.fieldMap["cutter_drive_gearbox_oil_saturation"] = d.CutterDriveGearboxOilSaturation
	d.fieldMap["underwater_pump_gearbox_oil_temperature"] = d.UnderwaterPumpGearboxOilTemperature
	d.fieldMap["underwater_pump_gearbox_oil_pressure"] = d.UnderwaterPumpGearboxOilPressure
	d.fieldMap["underwater_pump_gearbox_oil_saturation"] = d.UnderwaterPumpGearboxOilSaturation
	d.fieldMap["fuel_tank_40_level"] = d.FuelTank40Level
	d.fieldMap["mer_fuel_daily_tank_level"] = d.MerFuelDailyTankLevel
	d.fieldMap["fuel_tank_3_level"] = d.FuelTank3Level
	d.fieldMap["lubricating_oil_tank_5_level"] = d.LubricatingOilTank5Level
	d.fieldMap["hydraulic_oil_tank_7_level"] = d.HydraulicOilTank7Level
	d.fieldMap["auxiliary_fuel_daily_tank_level"] = d.AuxiliaryFuelDailyTankLevel
	d.fieldMap["fuel_tank_13_level"] = d.FuelTank13Level
	d.fieldMap["fuel_tank_3a_level"] = d.FuelTank3ALevel
	d.fieldMap["fuel_tank_4_level"] = d.FuelTank4Level
	d.fieldMap["sewage_tank_6_level"] = d.SewageTank6Level
	d.fieldMap["freshwater_tank_8_level"] = d.FreshwaterTank8Level
	d.fieldMap["dirty_oil_tank_11_level"] = d.DirtyOilTank11Level
	d.fieldMap["fuel_tank_12_level"] = d.FuelTank12Level
	d.fieldMap["freshwater_tank_26_level"] = d.FreshwaterTank26Level
	d.fieldMap["fuel_tank_4a_level"] = d.FuelTank4ALevel
}

func (d dredgerDataHl) clone(db *gorm.DB) dredgerDataHl {
	d.dredgerDataHlDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dredgerDataHl) replaceDB(db *gorm.DB) dredgerDataHl {
	d.dredgerDataHlDo.ReplaceDB(db)
	return d
}

type dredgerDataHlDo struct{ gen.DO }

type IDredgerDataHlDo interface {
	gen.SubQuery
	Debug() IDredgerDataHlDo
	WithContext(ctx context.Context) IDredgerDataHlDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDredgerDataHlDo
	WriteDB() IDredgerDataHlDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDredgerDataHlDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDredgerDataHlDo
	Not(conds ...gen.Condition) IDredgerDataHlDo
	Or(conds ...gen.Condition) IDredgerDataHlDo
	Select(conds ...field.Expr) IDredgerDataHlDo
	Where(conds ...gen.Condition) IDredgerDataHlDo
	Order(conds ...field.Expr) IDredgerDataHlDo
	Distinct(cols ...field.Expr) IDredgerDataHlDo
	Omit(cols ...field.Expr) IDredgerDataHlDo
	Join(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo
	Group(cols ...field.Expr) IDredgerDataHlDo
	Having(conds ...gen.Condition) IDredgerDataHlDo
	Limit(limit int) IDredgerDataHlDo
	Offset(offset int) IDredgerDataHlDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDredgerDataHlDo
	Unscoped() IDredgerDataHlDo
	Create(values ...*model.DredgerDataHl) error
	CreateInBatches(values []*model.DredgerDataHl, batchSize int) error
	Save(values ...*model.DredgerDataHl) error
	First() (*model.DredgerDataHl, error)
	Take() (*model.DredgerDataHl, error)
	Last() (*model.DredgerDataHl, error)
	Find() ([]*model.DredgerDataHl, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DredgerDataHl, err error)
	FindInBatches(result *[]*model.DredgerDataHl, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DredgerDataHl) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDredgerDataHlDo
	Assign(attrs ...field.AssignExpr) IDredgerDataHlDo
	Joins(fields ...field.RelationField) IDredgerDataHlDo
	Preload(fields ...field.RelationField) IDredgerDataHlDo
	FirstOrInit() (*model.DredgerDataHl, error)
	FirstOrCreate() (*model.DredgerDataHl, error)
	FindByPage(offset int, limit int) (result []*model.DredgerDataHl, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDredgerDataHlDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dredgerDataHlDo) Debug() IDredgerDataHlDo {
	return d.withDO(d.DO.Debug())
}

func (d dredgerDataHlDo) WithContext(ctx context.Context) IDredgerDataHlDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dredgerDataHlDo) ReadDB() IDredgerDataHlDo {
	return d.Clauses(dbresolver.Read)
}

func (d dredgerDataHlDo) WriteDB() IDredgerDataHlDo {
	return d.Clauses(dbresolver.Write)
}

func (d dredgerDataHlDo) Session(config *gorm.Session) IDredgerDataHlDo {
	return d.withDO(d.DO.Session(config))
}

func (d dredgerDataHlDo) Clauses(conds ...clause.Expression) IDredgerDataHlDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dredgerDataHlDo) Returning(value interface{}, columns ...string) IDredgerDataHlDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dredgerDataHlDo) Not(conds ...gen.Condition) IDredgerDataHlDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dredgerDataHlDo) Or(conds ...gen.Condition) IDredgerDataHlDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dredgerDataHlDo) Select(conds ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dredgerDataHlDo) Where(conds ...gen.Condition) IDredgerDataHlDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dredgerDataHlDo) Order(conds ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dredgerDataHlDo) Distinct(cols ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dredgerDataHlDo) Omit(cols ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dredgerDataHlDo) Join(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dredgerDataHlDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dredgerDataHlDo) RightJoin(table schema.Tabler, on ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dredgerDataHlDo) Group(cols ...field.Expr) IDredgerDataHlDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dredgerDataHlDo) Having(conds ...gen.Condition) IDredgerDataHlDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dredgerDataHlDo) Limit(limit int) IDredgerDataHlDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dredgerDataHlDo) Offset(offset int) IDredgerDataHlDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dredgerDataHlDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDredgerDataHlDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dredgerDataHlDo) Unscoped() IDredgerDataHlDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dredgerDataHlDo) Create(values ...*model.DredgerDataHl) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dredgerDataHlDo) CreateInBatches(values []*model.DredgerDataHl, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dredgerDataHlDo) Save(values ...*model.DredgerDataHl) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dredgerDataHlDo) First() (*model.DredgerDataHl, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DredgerDataHl), nil
	}
}

func (d dredgerDataHlDo) Take() (*model.DredgerDataHl, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DredgerDataHl), nil
	}
}

func (d dredgerDataHlDo) Last() (*model.DredgerDataHl, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DredgerDataHl), nil
	}
}

func (d dredgerDataHlDo) Find() ([]*model.DredgerDataHl, error) {
	result, err := d.DO.Find()
	return result.([]*model.DredgerDataHl), err
}

func (d dredgerDataHlDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DredgerDataHl, err error) {
	buf := make([]*model.DredgerDataHl, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dredgerDataHlDo) FindInBatches(result *[]*model.DredgerDataHl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dredgerDataHlDo) Attrs(attrs ...field.AssignExpr) IDredgerDataHlDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dredgerDataHlDo) Assign(attrs ...field.AssignExpr) IDredgerDataHlDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dredgerDataHlDo) Joins(fields ...field.RelationField) IDredgerDataHlDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dredgerDataHlDo) Preload(fields ...field.RelationField) IDredgerDataHlDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dredgerDataHlDo) FirstOrInit() (*model.DredgerDataHl, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DredgerDataHl), nil
	}
}

func (d dredgerDataHlDo) FirstOrCreate() (*model.DredgerDataHl, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DredgerDataHl), nil
	}
}

func (d dredgerDataHlDo) FindByPage(offset int, limit int) (result []*model.DredgerDataHl, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dredgerDataHlDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dredgerDataHlDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dredgerDataHlDo) Delete(models ...*model.DredgerDataHl) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dredgerDataHlDo) withDO(do gen.Dao) *dredgerDataHlDo {
	d.DO = *do.(*gen.DO)
	return d
}
